# .goreleaser.yml
# Visit https://goreleaser.com for documentation on how to customize this
# behavior.
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy

# The builds section is intentionally left empty.
# GoReleaser will not build any binaries, and will instead use the artifacts
# prepared in the `release-files` directory by the GitHub Actions workflow.
builds:
  - skip: true

# The archives section is also skipped, as we are dealing with raw binaries
# that are not archived.
archives:
  - id: lyocell
    files:
      - none*

# nfpm packages are not used in this project.
nfpms:
  - id: packages
    file_name_template: '{{ .ConventionalFileName .Amd64 }}'
    homepage: https://github.com/wilhg/lyocell
    maintainer: wilhg
    description: High-performance load testing tool (k6 clone) on Java 25 & GraalVM
    license: MIT
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: release-files/lyocell-linux-amd64
        dst: /usr/local/bin/lyocell
        file_info:
          mode: 0755

# This is where we configure the GitHub release.
release:
  # The action will pick up the correct git tag.
  github:
    owner: wilhg
    name: lyocell

  # We can customize the name of the release.
  name_template: "Release {{.Tag}}"

  # We can also add a header to the release notes.
  header: |
    ## Lyocell {{.Tag}}

  # This section defines which files should be uploaded as release assets.
  # We use globs to find the binaries we prepared in the `release-files` dir.
  artifacts:
    - path: release-files/lyocell-linux-amd64
    - path: release-files/lyocell-macos-aarch64
    - path: release-files/lyocell-windows-amd64.exe

# This checksums section will generate a file with SHA256 checksums for all
# our release assets.
checksum:
  name_template: 'checksums.txt'

# This section configures the Homebrew tap.
brews:
  - name: lyocell
    # Points to your new Homebrew tap repository.
    tap:
      owner: wilhg
      name: lyocell-tap
    homepage: "https://github.com/wilhg/lyocell"
    description: "High-performance load testing tool (k6 clone) on Java 25 & GraalVM"
    license: "MIT"
    # GoReleaser will automatically create and push a formula file to the tap
    # repository that downloads the correct binary for the user's platform.
    install: |
      bin.install "lyocell"

# This section configures the Scoop bucket.
scoops:
  - name: lyocell
    # Points to your new Scoop bucket repository.
    bucket:
      owner: wilhg
      name: lyocell-scoop
    homepage: "https://github.com/wilhg/lyocell"
    description: "High-performance load testing tool (k6 clone) on Java 25 & GraalVM"
    license: "MIT"
# This signs section configures how to sign and upload packages to Cloudsmith.
signs:
  - cmd: goreleaser-cloudsmith
    env:
      - CLOUDSMITH_TOKEN={{ .Env.CLOUDSMITH_TOKEN }}
      - CLOUDSMITH_OWNER=wilhg
      - CLOUDSMITH_REPO=lyocell
    artifacts: all
    output: true